config/routes.rb
Rails.application.routes.draw do
  root 'static#home'
  resources :static
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, except: [:index]
  get :details, to: 'users#details'
  resources :programs, only: [:new, :index, :create, :destroy]
  resources :groups, except: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :programs
  has_one_attached :avatar

  validates :name, presence: true, uniqueness: true, length: { in: 3..10 }
  validate :acceptable_avatar

  scope :order_by_name, -> { order('name') }

  def acceptable_avatar
    return errors.add(:avatar, 'is too big') unless avatar.byte_size <= 1.5.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    return errors.add(:avatar, 'must be a JPEG or PNG') unless acceptable_types.include?(avatar.content_type)
  end
end

app/models/program.rb
class Program < ApplicationRecord
  belongs_to :user
  belongs_to :author, class_name: 'User', foreign_key: 'user_id'
  belongs_to :group, foreign_key: 'group_id', optional: true

  validates :name, presence: true, length: { in: 3..30 }
  validates :amount, presence: true, numericality: { only_integer: true }

  scope :ordered_by_most_recent, -> { order(created_at: :desc) }
  scope :no_group, -> { where group_id: nil }
  scope :grouped, -> { where.not(group_id: nil) }
  scope :daily, -> { where(created_at: Time.now.beginning_of_day..Time.zone.now) }
  scope :weekly, -> { where(created_at: Time.now.prev_day(7)..Time.zone.now) }
  scope :monthly, -> { where(created_at: Time.now.prev_month(1)..Time.zone.now) }
  scope :yearly, -> { where(created_at: Time.now.prev_year(1)..Time.zone.now) }

  def self.total_hours
    sum(:amount)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { in: 3..10 }
  validates_presence_of :email
  validates_presence_of :password
  validates_uniqueness_of :email
  validate :acceptable_avatar

  has_one_attached :avatar
  has_many :programs, inverse_of: 'author', dependent: :destroy
  has_many :programs, -> { includes :group }, class_name: 'Program'

  def acceptable_avatar
    return errors.add(:avatar, 'is too big') unless avatar.byte_size <= 1.5.megabyte

    acceptable_types = ['image/jpeg', 'image/png']
    return errors.add(:avatar, 'must be a JPEG or PNG') unless acceptable_types.include?(avatar.content_type)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def require_login
    return true unless session[:user_id].nil?

    flash[:notice] = 'You most log in to access this page.'

    redirect_to new_session_path
    false
  end

  def current_user
    @current_user = User.find(session[:user_id])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def new
    @group = Group.new
  end

  def index
    @groups = Group.all.order_by_name
  end

  def create
    @group = Group.create(group_params)

    if @group.save
      redirect_to groups_path, notice: 'group created'
    else
      render :new
    end
  end

  def show
    @user = User.find(session[:user_id])
    @group = Group.find(params[:id])
    @programs = @group.programs.ordered_by_most_recent
    @group_amount = @programs.total_hours
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    @group = Group.find(params[:id])
    if @group.update(group_params)
      redirect_to @group
    else
      render :edit
    end
  end

  def destroy
    @group = Group.find(params[:id])
    @group.destroy
    redirect_to groups_path
  end

  def group_params
    params.require(:group).permit(:name, :avatar)
  end
end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :require_login
  before_action :set_caller, only: [:index]
  before_action :set_title, only: [:index]

  def new
    @program = Program.new
  end

  def index
    if @caller == 'ungrouped'
      @programs = current_user.programs.no_group.ordered_by_most_recent
      @programs_amount = current_user.programs.no_group.total_hours
    else
      @programs = current_user.programs.ordered_by_most_recent
      @programs_amount = current_user.programs.total_hours
    end
  end

  def create
    @program = current_user.programs.create(program_params)

    if @program.save
      redirect_to programs_path(caller: 'full'), notice: 'program successfully created!'
    else
      render :new
    end
  end

  def destroy
    @program = Program.find(params[:id])
    @program.destroy
    redirect_to programs_path(caller: 'full')
  end

  private

  def program_params
    params.require(:program).permit(:name, :amount, :group_id)
  end

  def set_caller
    @caller = params[:caller]
  end

  def set_title
    @title = @caller == 'full' ? 'My TV Shows' : 'My Shuffled TV Shows'
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :require_login, except: %i[new create]

  def new
    render :new
  end

  def create
    input = params[:name]
    @user = User.find_by(name: params[:name])

    if @user
      session[:user_id] = @user.id
      redirect_to @user, alert: 'You have successfully logged in.'
    else
      flash[:alert] = "User #{input} is not found!"
      redirect_to new_session_path
    end
  end

  def destroy
    reset_session
    flash[:notice] = 'You have successfully logged out.'
    redirect_to root_path
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: %i[new create]
  before_action :set_programs, only: [:details]
  before_action :set_caller, only: [:details]

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
    @button = 'Sign Up'
  end

  def create
    @user = User.create(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: 'User was successfully created.'
    else
      render :new
    end
  end

  def edit
    @user = User.find(params[:id])
    @button = 'Update'
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to @user, notice: 'User sucessfully updated'
    else
      render :edit
    end
  end

  def details
    if @caller == 'day'
      @day = @progs.daily.total_hours
      flash[:notice] = "Watched Today: #{@day} hours"
    elsif @caller == 'week'
      @week = @progs.weekly.total_hours
      flash[:notice] = "Watched This Week: #{@week} hours"
    else
      @month = @progs.monthly.total_hours
      flash[:notice] = "Watched This Month: #{@month} hours"
    end
    redirect_to current_user
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :avatar)
  end

  def set_programs
    @progs = current_user.programs
  end

  def set_caller
    @caller = params[:caller]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def add_user_avatar(obj)
    if obj.avatar.attached?
      image_tag obj.avatar, class: 'mt-3 rounded-circle avatar', width: 120, height: 120
    else
      image_tag 'sample-profile2.png', alt: 'default image', width: 100, height: 100, class: 'rounded-circle mt-3'
    end
  end

  def add_program_item(obj)
    add_group_icon(obj) if obj
  end

  private

  def add_group_icon(obj)
    if obj.avatar.attached?
      image_tag obj.avatar, class: 'avatar', width: 70, height: 70
    else
      image_tag 'sample-group.jpg', alt: 'default image', width: 70, height: 70
    end
  end
end

app/views/groups/_form.html.erb
<% if @group.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @group.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @group do |f| %>

  <div class="form-group">
    <%= f.text_field :name, placeholder: 'Name', autofocus: true, class: "w-100"  %>
  </div>
  <div class="form-group">
    <%= label_tag 'Icon (Optional max-size: 1.5Mb)', class: "text-color" %>
    <%= f.file_field :avatar, direct_upload: true, class: "w-100" %>  
  </div>

  <div class="actions">
    <%= f.submit class: "log d-block border rad p-2 text-center text-white bg-blue w-100"  %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<div class="new-group bg-eee vh-100">
  <div class="new-group-nav">
    <div class="menu d-flex justify-content-between align-items-center p-2">
        <%= link_to :back do %>
          <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
        <% end %>
        <h4 class="title m-0">Update group</h4>
        <span><%= link_to 'Cancel', groups_path %></span>
      </div>
  </div>
  <div class="container form-new d-flex flex-column justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/index.html.erb
<div class= "group-list min-vh-100 bg-blue">

  <div class= "groups-list_head sticky-top">
    <div class="menu d-flex justify-content-between align-items-center p-2">
      <%= link_to user_path(session[:user_id]) do %>
        <span><i class="fa fa-bars fa-2x font-weight-lighter" aria-hidden="true"></i></span>
      <% end %>
      <h4 class="title m-0">Groups</h4>
      <span><i class="fa fa-search fa-2x" aria-hidden="true"></i></span>
    </div>
  </div>

  <div class= "group-list_content">

    <% @groups.each do |group|%>
      
      <div class= "groups-list_card d-flex justify-content-center">
        <%= link_to group do %>
          <%= add_group_icon(group) %>
        <% end %> 

        <%= link_to group do %>
          <div class="group_details ml-2">
            <p class="mt-3 mb-0"><%= group.name.capitalize %></p>
            <small class="mt-2 d-block small"><%= group.created_at.strftime("%A %B %d, %Y") %></small>
          </div>
        <% end %>
      </div>
      <hr class="w-25 my-0">
    <% end %>

    <div class="add-btn">
      <%= link_to 'Add new group', new_group_path, class:"btn border border-white btn-lg btn-block text-white btn-outline-success" %>
    </div>
  </div>

<div>

app/views/groups/new.html.erb
<div class="new-group bg-eee vh-100">
  <div class="new-group-nav">
    <div class="menu d-flex justify-content-between align-items-center p-2">
        <%= link_to :back do %>
          <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
        <% end %>
        <h4 class="title m-0">New group</h4>
        <span><%= link_to 'Cancel', groups_path %></span>
      </div>
  </div>
  <div class="container form-new d-flex flex-column justify-content-center">
    <%= render 'form' %>
  </div>
</div>

app/views/groups/show.html.erb
<div class= "group__programs-list bg-eee">

  <div class= "group__programs-list_head sticky-top">
    <div class="group__programs-list_nav d-flex justify-content-between align-items-center p-2">
      <%= link_to groups_path do %>
        <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
      <% end %>

      <h5 class="title m-0"><%= @group.name.capitalize %></h5>

      <%= link_to edit_group_path do %>
        <span><i class="fa fa-pencil-square-o" aria-hidden="true"></i></span>
      <% end %>
    </div>

    <div class="group__programs-list_amount_watched d-flex justify-content-between align-items-center py-3 px-2 bg-light text-color">
      <p class="m-0">Total hours watched:</p>
      <p class="m-0"><b><%= @group_amount %> hrs</b></p>
    </div>
  </div>

  <div class= "group__programs-list_content">

    <% @group.programs.each do |program|%>
      <div class= "group__programs-list_card d-flex justify-content-between">
        <div class="program_details d-flex">
          <%= add_group_icon(@group) %>

          <div class="program_details__details ml-2">
            <p class="mt-2 mb-0"><%= program.name.capitalize %></p>
            <small class="mt-1 d-block small">Author: <%= program.author.name %></small>
            <small class="d-block small"><%= program.created_at.strftime("%A %B %d, %Y") %></small>
          </div>
        </div>
        <p class="mb-0 mt-2"><%= program.amount %> hrs</p>
      </div>
    <% end %>

    <div class="add-btn">
      <%= link_to 'Add new program', new_program_path, class:"btn border border-white btn-lg btn-block text-white btn-outline-success" %>
    </div>
  </div>

<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Wotchd</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="">

    <!-- <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: name, class:"m-0 bg-success" %>
    <% end %> -->
   

    <%= yield %>

   </body>
</html>

app/views/programs/index.html.erb
<div class= "programs-list min-vh-100 bg-eee">

  <div class= "programs-list_head sticky-top">
    <div class="menu d-flex justify-content-between align-items-center p-2">
      <%= link_to user_path(session[:user_id]) do %>
        <span><i class="fa fa-bars" aria-hidden="true"></i></span>
      <% end %>
      <h4 class="title m-0"><%= @title %></h4>
      <span><i class="fa fa-search" aria-hidden="true"></i></span>
    </div>
    <div class="amount_watched d-flex justify-content-between align-items-center py-3 px-2 bg-light text-color">
      <p class="m-0">Total hours watched:</p>
      <p class="m-0"><b><%= @programs_amount %> hrs</b></p>
    </div>
  </div>

  <div class= "programs-list_content">

    <% @programs.each do |program|%>
      <div class= "programs-list_card d-flex justify-content-between">
        <div class="program_details d-flex">
          <%= add_program_item(program.group) %>

          <div class="program_details__details ml-2">
            <p class="mt-3 mb-0"><%= program.name.capitalize %></p>
            <small class="mt-2 d-block small"><%= program.created_at.strftime("%A %B %d, %Y") %></small>
          </div>
        </div>

        <div class="d-flex flex-column">
          <p class="mb-1 mt-3"><%= program.amount %> hrs</p>
          <%= link_to program_path(program.id), class: "align-self-end", method: :delete, data: { confirm: 'do you want to delete this program?'} do %>
            <i class="fa fa-trash-o" aria-hidden="true"></i>
          <% end %>
        </div>
      </div>
    <% end %>

    <div class="add-btn">
      <%= link_to 'Add new program', new_program_path(), class:"btn border border-white btn-lg btn-block text-white btn-outline-success" %>
    </div>
  </div>

<div>

app/views/programs/new.html.erb
<div class="new-program bg-eee vh-100">
  <div class="new-program-nav">
    <div class="menu d-flex justify-content-between align-items-center p-2">
        <%= link_to :back do %>
          <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
        <% end %>
        <h4 class="title m-0">New program</h4>
        <span><%= link_to 'Cancel', programs_path(caller: 'full') %></span>
      </div>
  </div>

  <div class="container form-new d-flex flex-column justify-content-center">

    <% if @program.errors.any? %>
      <div class="alert alert-danger">
        <ul>
          <% @program.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    

    <%= form_for @program do |f| %>

      <div class="form-group">
        <%= f.text_field :name, placeholder: 'Program name', autofocus: true, class: "w-100" %>
      </div>
      <div class="form-group">
        <%= f.text_field :amount, placeholder: 'Hours watched', autofocus: true, class: "w-100" %>
      </div>
      <div class="form-group">
        <%= label_tag :group, "Group", class: "text-color" %>
        <div>
          <%= f.select :group_id, Group.pluck(:name, :id), include_blank: "Select group", class: "d-block w-100" %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit 'Add a program', class: "log d-block border rad p-2 text-center text-white bg-blue w-100"  %>
      </div>
    <% end %>

  </div>
</div>

app/views/users/_form.html.erb
<% if @user.errors.any? %>
  <div class="alert alert-danger">
    <ul>
      <% @user.errors.full_messages.each do |error| %>
        <li><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @user do |f| %>
  <div class="form-group">
    <%= f.label 'Upload picture (Optional max-size: 1.5Mb)', class: "upload-label" %>
    <%= f.file_field :avatar, direct_upload: true, class: "form-control-file" %>
  </div>
  <div class="form-group">
    <%= f.text_field :name, placeholder: 'Name', autofocus: true, class: "w-100" %>
  </div>
  <div class="form-group">
    <%= f.email_field :email, placeholder: 'Email', class: "w-100" %>
    <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
  </div>
  <div class="form-group">
    <%= f.password_field :password, placeholder: 'Password', class: "w-100" %>
  </div>

  <div class="actions">
    <%= f.submit @button, class: "log d-block border rad p-2 text-center text-white bg-blue w-100"  %>
  </div>
<% end %>

app/views/users/edit.html.erb
<div class="new-user bg-eee vh-100">
  <div class="new-user-nav">
    <div class="menu d-flex justify-content-between align-items-center p-2">
        <%= link_to root_path do %>
          <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
        <% end %>
        <h4 class="title m-0">Update account</h4>
        <span><%= link_to 'Cancel', root_path %></span>
      </div>
  </div>

  <div class="container form-new d-flex flex-column justify-content-center">
    <div><%= render 'form' %></div>
  </div>
</div>

app/views/users/new.html.erb
<div class="new-user bg-eee vh-100">
  <div class="new-user-nav">
    <div class="menu d-flex justify-content-between align-items-center p-2">
        <%= link_to root_path do %>
          <span><i class="fa fa-arrow-left" aria-hidden="true"></i></span>
        <% end %>
        <h4 class="title m-0">Register</h4>
        <span><%= link_to 'Cancel', root_path %></span>
      </div>
  </div>

  <div class="container form-new d-flex flex-column justify-content-center">
    <div><%= render 'form' %></div>
  </div>
</div>

app/views/users/show.html.erb
<div class="profile d-flex flex-column">
  <div class="profile-header text-center align-self-center">
    <figure class="d-flex justify-content-center">
      <%= add_user_avatar(@user) %>
    </figure>
    <h4 class="username"><%= @user.name.capitalize %></h4>
  </div>

  <div class="d-flex mt-5 align-self-end align-self-md-center">
    <div class="profile-content">
      <h1 class= "d-flex">
        <i class="fa fa-television d-block" aria-hidden="true"></i>
        <div class="align-self-center">
          <%= link_to 'All my TV Shows', programs_path(caller: 'full') %>
        </div>
      </h1>

      <hr>

      <h1 class= "d-flex">
        <i class="fa fa-random d-block" aria-hidden="true"></i>
        <div class="align-self-center">
          <%= link_to 'All my Shuffled TV Shows', programs_path(caller: 'ungrouped') %>
        </div>
      </h1>

      <hr>

      <h1 class= "d-flex">
        <i class="fa fa-object-group d-block" aria-hidden="true"></i>
        <div class="align-self-center">
          <%= link_to 'All Groups', groups_path %>
        <div>
      </h1>

      <hr>

      <h1 class= "d-flex">
        <i class="fa fa-sign-out d-block" aria-hidden="true"></i>
        <div class="align-self-center">
          <%= link_to 'Log out', session_path(0), method: :delete %>
        <div>
      </h1>

    </div>

    <div class="resume d-flex flex-column justify-content-center p-2">
      <h6 class="text-center my-0 p-2"><%= link_to 'Today', details_path(caller: 'day') %></h6>
      <h6 class="text-center my-2 p-2"><%= link_to 'Week', details_path(caller: 'week') %></h6>
      <h6 class="text-center my-0 p-2"><%= link_to 'Month', details_path(caller: 'month')%></h6>
    </div>
  </div>
  
  <% if flash[:notice] %>
      <div class="alert alert-info container w-50 align-self-center text-center mt-5" role="alert">
        <p class="m-0"><%= notice %></p>
      </div>
  <% end %>

</div>